name = "irwin-studio-frontend"
type = "webpack"
account_id = ""
zone_id = ""
workers_dev = true
route = ""

[site]
bucket = "./build"
entry-point = "workers-site"

[env.staging]
name = "is-fe-staging"
bucket = "./build"
entry-point = "workers-site"
