name: Frontend Staging

on:
    pull_request:
        types:
        - closed

        branches:
        - staging

jobs:
  release:
    name: Frontend Staging
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Fetch Latest
        uses: actions/checkout@v2

      - name: Increase inotify watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache-id
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn libs
        id: irwin-studio-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-id.outputs.dir }}
          key: ${{ runner.os }}-irwin-studio-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-irwin-studio-cache-

      - name: Install Dependencies
        run: yarn --prefer--offline --frozen-lockfile

      # The double-double-dash (-- --) is required here because...
      # The second is for lerna to parse the flags to the npm client
      # The first one is so that the second '--' and the following flags are sent to the lerna command
      - name: Bootstrap Packages
        run: yarn lerna bootstrap -- -- --prefer-offline --frozen-lockfile

      - name: Build
        working-directory: ./packages/frontend
        run: yarn build
        env:
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}

      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ./packages/frontend
          environment: 'staging'
        env:
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          FB_API_KEY: ${{ secrets.FB_API_KEY }}
          FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
          FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
          FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
          FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
