name: Validate Backend

on:
  pull_request:
    paths:
      - packages/backend/**
    branches:
      - main
      - staging
  
jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Latest
        uses: actions/checkout@v2

      - name: Increase inotify watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache-id
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn libs
        id: irwin-studio-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-id.outputs.dir }}
          key: ${{ runner.os }}-irwin-studio-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-irwin-studio-cache-

      - name: Install Dependencies
        working-directory: ./packages/backend
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Test
        working-directory: ./packages/backend
        run: yarn test

      - name: Build
        working-directory: ./packages/backend
        run: yarn build
