name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Fetch Latest
        uses: actions/checkout@v2

      - name: Increase inotify watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Get yarn cache
        id: yarn-cache-id
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn libs
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-id.outputs.dir }}
          key: ${{ runner.os }}-v2-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-v2-yarn-cache-

      - name: Install Dependencies
        run: yarn

      - name: Test - lint
        run: yarn test:lint

      - name: Test - types
        run: yarn test:types

      - name: Build
        run: yarn build
